feat: POST API, registerRestaurant
Cheffi-Git/Cheffi-Server pull request #160
Opened 2023-12-21 14:46 UTC by seulee0862

2023-12-24 10:30 UTC, wnsvy607 requested changes
## 컨벤션
컨벤션을 맞추기 위해서
커밋 메시지와 PR 타이틀의 
첫글자를 대문자로 `POST /a/b` API 포맷(백틱사용)으로 바꿔주세요~

## 도로명 주소
현재 식당의 주소로서 도로명 주소만 사용한다고 합니다. 이 사항 참고해서 검증(Validation)하시면 될것 같아요.

2023-12-24 10:30 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/request/RegisterRestaurantRequest.java
주소 정보는 특별한 이유가 없다면 여러 필드를 나열하는 것보다 
`DetailedAddress` 하나로 받으면 될것 같네요

2023-12-24 10:30 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/service/RestaurantService.java
`registerRestaurant` 이름의 메서드가 2개인데 그 용도가 확실히 다릅니다.
인자도`RegisterRestaurantRequest` 이므로 쓰는 입장에서 헷갈릴 것 같네요
메서드 혹은 매개변수 클래스(RegisterRestaurantRequest)의 네이밍을 변경을 제안드립니다.

2023-12-24 10:30 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/service/RestaurantService.java
> +			throw new BusinessException(ErrorCode.RESTAURANT_ALREADY_REGISTERED);
상세 주소를 나타내는 `DetailedAddress` 는 다른 식당이더라도 동일할 수 있습니다. 따라서 해당 로직은 제거해주는게 바람직하다고 생각합니다.

2023-12-24 10:30 UTC, wnsvy607 commented on src/main/java/com/cheffi/common/code/ErrorCode.java
에러 코드가 겹치는 부분이 있었군요 좋은 수정입니다.

2023-12-24 10:30 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/controller/RestaurantController.java
> +	@Tag(name = "Restaurant")
그냥 식당 등록이라고 하기보단 API의 목적을 명시하기 위해 임시 식당 등록, 식당 등록 신청 등으로 적어 놓는 것이 바람직해보입니다.

2023-12-26 10:58 UTC, wnsvy607 requested changes

2023-12-26 10:58 UTC, wnsvy607 commented on src/main/java/com/cheffi/common/constant/DetailedAddress.java
> +	@JsonIgnore
해당 API는 의도적으로 노출한거라 해당 어노테이션 제거 부탁드립니다.

2023-12-26 10:58 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/controller/RestaurantController.java
> +	@Tag(name = "Restaurant")
"동일한 주소로 공공데이터가 존재하는경우(=검색화면에 나오는 주소인경우) 에러 발생"
이 부분은 검증하지 않기로 하지 않았었나요?

2023-12-26 10:58 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/domain/Restaurant.java
> +	public static Restaurant registerTempRestaurant(RegisterRestaurantRequest request, DetailedAddress detailedAddress) {
`RegisterRestaurantRequest` 내부에 이미 detailedAddress 필드가 있어 매개변수로 `DetailedAddress`를 따로 받아올 필요는 없어 보이네요

2023-12-26 10:58 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/request/RegisterRestaurantRequest.java
> +
`@Valid` 어노테이션 붙여주세요

2023-12-31 15:18 UTC, seulee0862 commented on src/main/java/com/cheffi/review/dto/request/RegisterRestaurantRequest.java
> +
@Valid @RequestBody RegisterRestaurantRequest request 여기에 붙여서 검증하고 있습니다

2023-12-31 15:19 UTC, seulee0862 commented on src/main/java/com/cheffi/review/domain/Restaurant.java
> +	public static Restaurant registerTempRestaurant(RegisterRestaurantRequest request, DetailedAddress detailedAddress) {
그렇네요 수정하겠습니다

2024-01-01 09:51 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/domain/Restaurant.java
> +	public static Restaurant registerTempRestaurant(RegisterRestaurantRequest request, DetailedAddress detailedAddress) {
네 로직제거한건 확인했는데, 스웨거 문서 부분에는 저렇게 그대로 적혀있어서요

2024-01-01 11:14 UTC, closed without merging