Feat: add `POST /api/v1/restaurants`
Cheffi-Git/Cheffi-Server pull request #168
Opened 2024-01-01 11:13 UTC by seulee0862

2024-01-03 01:20 UTC, wnsvy607 requested changes

2024-01-03 01:20 UTC, wnsvy607 commented on src/main/java/com/cheffi/common/constant/DetailedAddress.java
> -	@NotNull
`@NotNull` 어노테이션은 DB에 not null을 걸어주므로 제거하면 안될것 같아요

2024-01-03 01:20 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/controller/RestaurantController.java
> +	@PreAuthorize("hasRole('USER')")
이 API가 식당 등록의 일부이므로 프로필이 등록된 유저인지도 검증할 필요가 있어보여요
리뷰 등록하는 API 참고하셔서 프로필 등록여부도 검증해주세요

2024-01-07 07:15 UTC, seulee0862 commented on src/main/java/com/cheffi/review/controller/RestaurantController.java
> +	@PreAuthorize("hasRole('USER')")
알겠습니다~

2024-01-09 16:18 UTC, wnsvy607 approved these changes

2024-01-09 16:18 UTC, merged