Feature/review
Cheffi-Git/Cheffi-Server pull request #25
Opened 2023-07-27 17:30 UTC by seulee0862

[body]
/api/v1/review?id={}
controller, dto, mockDto Method 추가

PR되면 이대로 더 진행하겠습니다

응답값 포맷
```
{
  "data": {
    "reviewid": 5,
    "title": "리뷰 제목",
    "text": "리뷰 내용",
    "bookmark": true,
    "restaurant": {
      "detail": "맛집 상가명",
      "town": "시/도",
      "city": "구/시/군",
      "province": "동/읍/면/리",
      "name": "상세주소"
    },
    "reviewphotos": [
      {
        "photoOrderInReview": 1,
        "reviewUrl": "www.photoUrl1"
      },
      {
        "photoOrderInReview": 2,
        "reviewUrl": "www.photoUrl2"
      }
    ],
    "ratings": [
      {
        "ratingType": "GOOD",
        "score": 5
      },
      {
        "ratingType": "GOOD",
        "score": 5
      },
      {
        "ratingType": "GOOD",
        "score": 5
      }
    ]
  },
  "code": 200,
  "message": "success"
}
```

2023-07-28 07:44 UTC, wnsvy607 requested changes

2023-07-28 07:44 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +    private Long    reviewid;
typo

2023-07-28 07:44 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +    private List<ReviewPhotosValue>  reviewphotos;
typo

2023-07-28 07:44 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +    private boolean bookmark;
boolean 값은 과거분사형으로 해주시기 바랍니다.

2023-07-28 07:44 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/domain/Review.java
> +import jakarta.persistence.*;
코딩 컨벤션이 달라서 임포트 옵티마이즈할 때마다 이런 식의 불필요한 커밋이 발생합니다.

https://naver.github.io/hackday-conventions-java/ 
여기서 코딩 컨벤션 적용 부탁드립니다.

2023-07-28 07:44 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/controller/ReviewController.java
> +    public ApiResponse<GetReviewResponseDto> getRivew(GetReviewRequestDto requestDto) {
오타 신경써주세요

2023-07-28 07:44 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/controller/ReviewController.java
> +        return ApiResponse.success(createMockDto());
굳이 메서드로 빼서 분리할 정도로 복잡한 코드는 아닌거 같습니다.

2023-07-28 07:44 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +                                          boolean bookmark) {
설계 잘하셨는데, 저는 DTO에 비지니스 로직이 들어가면 안된다고 생각합니다.

2023-07-28 07:44 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +    public static class RestaurantValue {
재사용성을 생각하면 
이너 클래스보다는 따로 클래스를 하나 빼는 것이 나아 보입니다.
그리고 DetailedAddress 자체가 값 타입이기 때문에 굳이 해체하여 표시할 필요는 없습니다.

2023-07-28 07:44 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +            this.photoOrderInReview = reviewPhoto.getId();
PK와 givenOrder 값을 혼동하셨네요 수정바랍니다

2023-07-28 07:44 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +    public static class RatingValue {
점수 히스토리를 DTO 로 만들어서 보내주는 것보다
그냥 총점 하나를 필드로 보여주는게 합리적이지 않을까요?

2023-07-28 08:43 UTC, seulee0862 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +    public static class RatingValue {
합리적이네요 수정하겠습니다.

2023-07-28 08:44 UTC, seulee0862 commented on src/main/java/com/cheffi/review/controller/ReviewController.java
> +    public ApiResponse<GetReviewResponseDto> getRivew(GetReviewRequestDto requestDto) {
오타가 많네요 커밋전에 꼭 검토할게요

2023-07-28 08:45 UTC, seulee0862 commented on src/main/java/com/cheffi/review/controller/ReviewController.java
> +        return ApiResponse.success(createMockDto());
맞네요 수정하겠습니다

2023-07-28 08:51 UTC, seulee0862 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +                                          boolean bookmark) {
Mock Data 만드는 로직은 나중에 삭제해서 이부분만 제외하고 생각하겠습니다.

of의 메서드에서 전달값을 새로운 List로 재가공하는 부분을 비즈니스 로직이라고 이해했습니다.
수정하고 dto에서 비즈니스 로직 다루는건 지향하도록 하겠습니다. 

```java
public static GetReviewResponseDto of(Review searchedReview,
                                          boolean bookmark) {

        RestaurantValue restaurantValue = new RestaurantValue(searchedReview.getRestaurant());

        // 이부분
        List<ReviewPhotosValue> reviewPhotoValues = searchedReview.getReviewPhotos()
                .stream()
                .map(ReviewPhotosValue::new)
                .toList();

        List<RatingValue> ratingValues = searchedReview.getRatings()
                .stream()
                .map(RatingValue::new)
                .toList();
        //

        return GetReviewResponseDto.builder()
                .reviewid(searchedReview.getId())
                .title(searchedReview.getTitle())
                .text(searchedReview.getText())
                .bookmark(bookmark)
                .restaurant(restaurantValue)
                .reviewphotos(reviewPhotoValues)
                .ratings(ratingValues)
                .build();

    }
```

2023-07-28 08:53 UTC, seulee0862 commented on src/main/java/com/cheffi/review/domain/Review.java
> +import jakarta.persistence.*;
옙 
(참조 내용)
```
클래스를 import할때는 와일드카드(*) 없이 모든 클래스명을 다 쓴다. static import에서는 와일드카드를 허용한다.

ex)
import java.util.*; 
->
import java.util.List;
import java.util.ArrayList;
```

2023-07-28 08:59 UTC, seulee0862 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +    public static class RestaurantValue {
Inner class의 사용목적이 응답 값에 필요한 필드만 노출시키기 위함인데
재사용성을 위해서 따로 관리하는 건 어렵지 않을까요??

생각하는 예시는 전체 조회에서는 review의 Restaurant 클래스의 A 필드만 보여주면 되지만
단일 조회에서는 Restaurant 클래스의 A, B 필드 둘 다 보여줘야 할 경우입니다.

2023-07-28 09:00 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +                                          boolean bookmark) {
getRestaurant(), getReviewPhotos(), getRatings() 등 메서드를 호출하는 것 자체가 비즈니스 로직입니다.
그리고 Lazy Fetch 자체를 DTO 내부에서 호출하는 행위는 상당히 위험합니다.

2023-07-28 09:00 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +                                          boolean bookmark) {
해당 값을 List<T>, T 의 형태로 매개변수로 받을 것을 권장합니다.

2023-07-28 09:02 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +                                          boolean bookmark) {
MockData 관련한 부분은 어차피 나중에 지울거라 생각하고 있기에 피드백 대상은 아닙니다.

2023-07-28 09:04 UTC, seulee0862 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +    private boolean bookmark;
알겠습니다

2023-07-28 09:37 UTC, seulee0862 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +                                          boolean bookmark) {
영속성 컨텍스트 범위까지는 전혀 고려하지 못했는데 좋은 피드백 감사합니다.

2023-07-28 09:38 UTC, seulee0862 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +                                          boolean bookmark) {
"해당 값을 List, T 의 형태로 매개변수로 받을 것을 권장합니다." 권장하는 이유가 무엇인가요?
바꾸기 싫은건 아니고 이해를 하면 다른 코드 작성시에도 적절하게 적용할 수 있을 것 같습니다~

2023-07-28 10:21 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +                                          boolean bookmark) {
Review가 필드로서 가지고 있는 다른 엔티티를 DTO 내부에서 가져온다는 것 자체가 비지니스 로직입니다.
DTO는 순전히 값을 표시하는 것으로서 외부에서 주입하는 값을 필드로서 저장하면 됩니다.

2023-07-28 10:24 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +    public static class RestaurantValue {
어렵다는 말이 잘 이해가 안됩니다.
그리고 예시에서도 
리뷰 전체 조회에서 굳이 Address가 들어가지 않을 이유는 없다고 생각합니다.

2023-07-28 10:25 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +    public static class RestaurantValue {
오히려 식당관련 정보에서 표시해야 할 필드가 생긴다면 
따로 구현할 경우 수정지점이 2군데 발생하므로 비효율적이라고 생각합니다.

2023-07-28 13:28 UTC, seulee0862 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +    public static class RestaurantValue {
예시를 다시 들겠습니다!

스스로 가정하고 있는 것이 
리뷰목록 조회시에는 text가 필요없고 단건 리뷰 조회시에는 text가 필요하다 인데요

ReviewValue라는 class를 공통으로 사용한다면 전체 리뷰목록에 반환값에도 text라는 값이 전달될텐데 

이렇게 하지 않기 위해서 전체조회의 dto에는 text가 없는 ReviewValue를
단건조회의 dto에는  text가 있는 ReviewValue를 InnerClass로 정의할 생각이었습니다.

정리하면
text뿐만아니라 ReviewValue를 공통으로 사용하고 있는 dto에서는 
사용하지 않더라도 Review 테이블의 모든 필듣를 항상 보여줄 수 밖에없다 입니다.

2023-07-28 13:36 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +    public static class RestaurantValue {
Restaurant에 관해 이야기 하는 것 아닌가요?
Review에 관한 것이라면 Text 정보가 길기 때문에 상기 내용에 동의하지만
Review 관련 정보는 현재 inner class로 선언된 것이 없습니다.

반면, Restaurant 정보는 다른 API에서도 충분히 쓰일 여지가 있다고 봅니다.

2023-07-28 14:51 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/domain/Review.java
> +import jakarta.persistence.*;
Appendix D: 편집기 설정
여기서 IDE에 적용 가능합니다

2023-07-28 15:31 UTC, seulee0862 commented on src/main/java/com/cheffi/review/dto/response/GetReviewResponseDto.java
> +    public static class RestaurantValue {
Dto안에 innerClass를 분리해서 재사용하는 것에 대해서
어떤 생각을 갖고 어렵다고 답한건지에 대해서 설명하고 있었습니다.

Restaurant 자체가 중요한 건 아니어서 필드명도 A, B라고 추상적으로 예시를 들었던건데
커밋한 코드랑 전혀 상관없는 예시를  사전 설명없이 해서 전달이 제대로 안됐나봐요

2023-07-29 09:45 UTC, wnsvy607 reviewed
여기까지만 진행하시고 나머지는 다른 PR에서 해주세요 코드양이 너무 많아요

2023-07-29 12:35 UTC, seulee0862 commented
넵

2023-07-31 10:31 UTC, seulee0862 commented
"add registerReview" 커밋이 섞여있는데
RegistReviewRequest Class추가되는 것 밖에 없어서 합쳐진 채로 올렸습니다.

2023-08-01 11:59 UTC, closed without merging