Feat: add searhReview, serarchReviews
Cheffi-Git/Cheffi-Server pull request #32
Opened 2023-08-01 11:38 UTC by seulee0862

#25  변경내역

2023-08-02 11:40 UTC, wnsvy607 requested changes
코멘트 확인 바랍니다.

2023-08-02 11:40 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/RestaurantInfoDto.java
> +    private String detail;
`DetailedAddress` 타입을 써주세요

2023-08-02 11:40 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/response/SearchReviewResponse.java
> +                                 List<ReviewPhotoInfoDto> reviewphotos,
오타

2023-08-02 11:40 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/request/RegisterReviewRequest.java
> +public class RegisterReviewRequest {
`WriteReviewRequest` 로 네이밍 변경해주세요
`Register` 는 부자연스럽습니다.

2023-08-03 00:12 UTC, seulee0862 commented on src/main/java/com/cheffi/review/domain/Review.java
> +    private Integer ratingCnt;
int로 올려야 했는데 수정을 못했네요 
Integer로 바꿔봤었던 이유는 조회하지 않는 경우라면 0대신 null이 오는게 맞을까 고민했었습니다.

2023-08-03 00:39 UTC, seulee0862 commented
* comment에 남긴 오류랑 변경
* 단건조회, 지역조회는 sercurty인증에 필요한 헤더값 삭제 

생각해보니까 단순 조회에 둘다 필요없을 것 같아서 삭제했습니다.

commit 좀 잘정리해서 보낼 수 있게 노력해볼게요!..

2023-08-03 12:25 UTC, wnsvy607 requested changes

2023-08-03 12:25 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/RestaurantInfoDto.java
> +@Getter @Setter
`@Setter`가 필요한 이유가 있나요?

2023-08-03 12:25 UTC, wnsvy607 commented on src/main/java/com/cheffi/review/dto/response/SearchReviewResponse.java
> +@Getter @Setter
세터

2023-08-03 13:10 UTC, seulee0862 commented on src/main/java/com/cheffi/review/dto/response/SearchReviewResponse.java
> +@Getter @Setter
..!

2023-08-04 05:04 UTC, wnsvy607 approved these changes

2023-08-04 05:04 UTC, merged