Refactor: git deploy_dev_ec2.yml
Cheffi-Git/Cheffi-Server pull request #46
Opened 2023-08-12 05:57 UTC by seulee0862

docker-compose.yml 기반으로 앱실행되도록 수정

2023-08-12 05:58 UTC, seulee0862 commented
docker-compose-helper의 목적이 무엇인가요?

2023-08-12 10:51 UTC, wnsvy607 requested changes

2023-08-12 10:51 UTC, wnsvy607 commented on .github/workflows/deploy_dev_ec2.yml
> +            cd /home/ec2-user/cheffifolder
배포 전 컨테이너 중지 및 이미지 삭제를 위해
`docker-compose down --rmi local` 명령어를 추가해주세요

2023-08-12 10:52 UTC, wnsvy607 commented
> docker-compose-helper의 목적이 무엇인가요? 해당 파일은 실행하진 않았습니다

단순히 JDK 17이 안깔린 환경에서 jar 파일 빌드를 위한 유틸리티 컨테이너를 만드는 도커 컴포즈 파일입니다.

배포시에 포함시키지 않아도 상관 없습니다.

2023-08-12 12:26 UTC, seulee0862 commented on .github/workflows/deploy_dev_ec2.yml
> +            cd /home/ec2-user/cheffifolder
docker-compose down --rmi local
docker-compose up --build -d 로 변경했습니다.

2023-08-14 02:08 UTC, wnsvy607 approved these changes

2023-08-14 02:08 UTC, merged