Feat: addFollow
Cheffi-Git/Cheffi-Server pull request #83
Opened 2023-09-11 06:39 UTC by seulee0862

2023-09-11 08:42 UTC, wnsvy607 requested changes

2023-09-11 08:42 UTC, wnsvy607 commented on src/main/java/com/cheffi/avatar/domain/Follow.java
> +    static public Follow createFollowRelationship(Avatar subject, Avatar target) {
public static 으로 재정렬하는 것이 나을 것 같습니다.

2023-09-11 08:42 UTC, wnsvy607 commented on src/main/java/com/cheffi/avatar/domain/Follow.java
> +        return new Follow(subject, target);
다음과 같은 불변식(검증 코드)를 추가하고 테스트 코드를 작성하는 것이 바람직해보입니다.
1. null 체크
2. subject와 target이 같은 경우

2023-09-11 08:42 UTC, wnsvy607 commented on src/main/java/com/cheffi/avatar/service/FollowService.java
> +		}
38-43줄에서 DB에 팔로우 객체가 이미 있는지 참거짓을 뽑는게 목적이라면

`findBySubjectAndTarget` 대신 Repository에 `existBySubjectAndTarget` 메서드를 새로 정의해 사용하는 것이 직관적이라고 생각합니다.
```
if(existBy~~~) {
throw new BusinessException(ErrorCode.ALREADY_FOLLOWED);
}
```
이런식으로 하는게 더 짧고, 직관적일듯합니다.

2023-09-11 08:42 UTC, wnsvy607 commented on src/main/java/com/cheffi/avatar/service/FollowService.java
> +		Follow createdFollow = followRepository.save(toCreateFollow);
toCreateFollow 변수는 인라인으로 `save` 메서드 안으로 넣는 것이 간결해보입니다.

2023-09-11 08:42 UTC, wnsvy607 commented on src/main/java/com/cheffi/avatar/service/FollowService.java
> +			createdFollow.getSubject().getId(),
`Follow` 객체를 매개변수를 받는  `AddFollowResponse` 생성자나 정적 팩터리 메서드를 생성한다면 
 추후 요구사항 변경으로 인한 API 변화에 더 쉬운 대응이 가능할 것 같습니다.

2023-09-11 08:42 UTC, wnsvy607 commented on src/test/java/com/cheffi/avatar/mock/MockAvatar.java
> +	public MockAvatar(Long id, String nickname, User user) {
일단 테스트 코드 작성 시도는 좋았습니다.

제 피드백은 도메인 객체를 상속받는 Mock 객체를 만들어 사용하는 방식은 번거롭고, 단위테스트와는 거리가 멉니다.
특히 지금처럼 리플렉션을 사용하는 경우는 최대한 지양해야 합니다. 

리플렉션에 관해서는, 제가 `MapValidationPolicyTest.ValidateTagsOfAvatar.setUp` 등과 같은 메서드에서 리플렉션을 이용한 테스트를 작성했는데 그것도 `@Spy`로 대체해서 작성하는 것이 바람직하고, 방법이 생각나면 리팩토링을 할 생각입니다.
1. Mock 객체를 사용하고 싶다면 직접 만들지 않고 `@Mock` 혹은 `@Spy` 어노테이션을 활용해서 써주세요.
2. 리플렉션 사용은 테스트 코드든 어디든 최대한 자제해야 합니다.

2023-09-11 09:20 UTC, seulee0862 commented on src/test/java/com/cheffi/avatar/mock/MockAvatar.java
> +	public MockAvatar(Long id, String nickname, User user) {
좋은 피드백 감사합니다

2023-09-13 06:04 UTC, wnsvy607 requested changes

2023-09-13 06:04 UTC, wnsvy607 commented on src/test/java/com/cheffi/avatar/service/FollowServiceTest.java
> +					.thenReturn(mock(Follow.class));
`any()` 와 `mock()`을 사용한 특별한 이유가 있나요?

2023-09-13 06:04 UTC, wnsvy607 commented on src/test/java/com/cheffi/avatar/mock/MockAddFollowResponse.java
해당 클래스 삭제바랍니다.

2023-09-14 06:34 UTC, seulee0862 commented
코드 push한 후에 코드 한줄만 수정하고 
이전 커밋하고 합쳐서 한번에 올라갈줄 알고

git rebase -i HEAD^
reabse ~~~ -> sqush ~~~ 변경
git push -f origin feature/follow 

이렇게 명령어 실행했는데  변경사항 커밋 이력을 잃어버렸습니다.
addfollow 수정, unfollow 추가 했습니다.

2023-09-15 06:17 UTC, wnsvy607 requested changes

2023-09-15 06:17 UTC, wnsvy607 commented on src/main/java/com/cheffi/avatar/service/FollowService.java
> +	public Avatar fetchFollow(Long followerId) {
파라미터 변수명 확인해주세요.

2023-09-15 06:17 UTC, wnsvy607 commented on src/test/java/com/cheffi/avatar/service/FollowServiceTest.java
> +			try {
해당절도 위에처럼 try-with-resource 구문으로 바꾸는게 좋을것 같아요

2023-09-15 06:20 UTC, wnsvy607 requested changes

2023-09-15 06:20 UTC, wnsvy607 commented on src/main/java/com/cheffi/avatar/service/FollowService.java
> +			.orElseThrow(() -> new BusinessException(ErrorCode.NOT_FOLLOWED));
해당 메서드도 public으로 빼는게 좋아보여요

2023-09-17 01:22 UTC, seulee0862 commented on src/main/java/com/cheffi/avatar/service/FollowService.java
> +			.orElseThrow(() -> new BusinessException(ErrorCode.NOT_FOLLOWED));
넵

2023-09-17 01:24 UTC, seulee0862 commented on src/main/java/com/cheffi/avatar/service/FollowService.java
> +	public Avatar fetchFollow(Long followerId) {
넵

2023-09-19 03:58 UTC, wnsvy607 requested changes

2023-09-19 03:58 UTC, wnsvy607 commented on src/main/java/com/cheffi/avatar/dto/response/UnfollowResponse.java
필요없는 import 문 커밋전에 꼭 정리해주세요

2023-09-19 03:58 UTC, wnsvy607 commented on src/test/java/com/cheffi/avatar/domain/FollowTest.java
> +			Follow mockFollow = mock(Follow.class);
@Mock 사용해주세요

2023-09-19 03:58 UTC, wnsvy607 commented on src/test/java/com/cheffi/avatar/service/FollowServiceTest.java
> +				Follow.class); MockedStatic<AddFollowResponse> staticAddFollowResponse = Mockito.mockStatic(
이 부분 라인 정렬이 너무 이상하게 되어 있는거 같아요

2023-09-19 05:33 UTC, seulee0862 commented on src/main/java/com/cheffi/avatar/dto/response/UnfollowResponse.java
넵

2023-09-19 11:39 UTC, wnsvy607 requested changes
`@DisplayName` 어노테이션에서 한쪽은 '성공' 이렇게 한글을 쓰고 한쪽은 'success' 영어를 쓰는데 통일해주세요.

2023-09-20 04:58 UTC, wnsvy607 approved these changes
GOOD

2023-09-20 04:59 UTC, merged