Feat: add getmyfollowee
Cheffi-Git/Cheffi-Server pull request #95
Opened 2023-09-21 03:47 UTC by seulee0862

2023-09-21 12:53 UTC, wnsvy607 requested changes

2023-09-21 12:53 UTC, wnsvy607 commented on src/main/java/com/cheffi/avatar/dto/response/AddFollowResponse.java
> +	public static AddFollowResponse of(Follow follow) {
of로 바꾼 이유가 있나요?

2023-09-21 12:53 UTC, wnsvy607 commented on src/main/java/com/cheffi/avatar/dto/response/GetFollowResponse.java
팔로우 목록을 조회할 때 본인의 프로필 사진도 같이 전송될 것이라 예상합니다.
`Avatar`의 `ProfilePhoto`의 `url`도 추가하면 좋을 것 같습니다.

2023-09-21 12:53 UTC, wnsvy607 commented on src/main/java/com/cheffi/avatar/service/FollowService.java
> +	public List<GetFollowResponse> getFollowee(Long avatarId) {
해당 메서드는 쿼리를 두 번 날리는데 딱히 그럴 필요가 없습니다.
followRepository에서 `avatarId`를 기준으로 조회하는 Jpql을 작성해보세요.
그리고 fetch Join으로 `Avatar`와 `ProfilePhoto`를 한 번에 가져오세요.

2023-09-22 02:37 UTC, seulee0862 commented on src/main/java/com/cheffi/avatar/dto/response/AddFollowResponse.java
> +	public static AddFollowResponse of(Follow follow) {
매개변수 1개에는 from 2개이상에는 of로 작성했는데요
다른 dto의 of메서드 보니 1매개변수 1개로 적용되고 있어
스타일 맞추려는 목적으로 바꿨습니다

2023-09-22 02:38 UTC, seulee0862 commented on src/main/java/com/cheffi/avatar/service/FollowService.java
> +	public List<GetFollowResponse> getFollowee(Long avatarId) {
알겠습니다

2023-09-25 02:58 UTC, wnsvy607 requested changes

2023-09-25 02:58 UTC, wnsvy607 commented on src/test/java/com/cheffi/avatar/service/FollowServiceTest.java
>  	}
AvatarService를 @Mock 으로 선언, FollowService는 @InjeckMocks를 사용해서 선언해주세요

2023-10-04 03:03 UTC, seulee0862 commented on src/test/java/com/cheffi/avatar/service/FollowServiceTest.java
>  	}
@Mock으로 생성한 avatarRepository, followRepository 두 객체를
 AvatarService에 넣고 FollowService에 넣은후에 테스트코드를 작성했는데
 
 FollowService에 @InjectMock AvatarService에 @Mock으로 초기화하면
 FollowService의 테스트코드에서 실행되는 avatarRepository stubing이 안되는데
 어떻게 해야할까요?

2023-10-05 09:37 UTC, seulee0862 commented on src/test/java/com/cheffi/avatar/service/FollowServiceTest.java
>  	}
FollowService에서 AvatarService의 메서드를 사용하면
AvatarService에서는 결과적으로 AvatarRepository의 메서드를 사용하기 때문에
AvararResoitory를 mock으로 만들고  스터빙 한이후에 AvatarService에 주입했었습니다.

AvatarService를 Mock으로 만든다음에 메섣드를 스터빙하면 AvararResoitory에서 오류가 나더라구요
한번 확인해보고 다시 해보겠습니다.

2023-10-09 12:29 UTC, wnsvy607 reviewed
잘 작성하셨는데 `criteria`는 장황함이라는 단점 때문에 전반적으로 잘 안쓰는 추세라
QueryDSL을 사용하는 것은 어떤가요?
구현은 https://giron.tistory.com/131 참고하시면 됩니다.

2023-10-10 07:12 UTC, seulee0862 commented
현재 코드보다 더 가독성이 좋아보여요. 참고해서 수정하겠습니다

2023-11-11 07:06 UTC, closed without merging